name: Build OpenSSL FIPS module

on:
    push:
    pull_request:
        branches: [ dist-git ]

jobs:
    mockBuild:
        runs-on: ubuntu-latest
        container:
            image: quay.io/rockylinux/rockylinux:9
            options: --privileged
        steps:
            - uses: actions/checkout@v3
            - name: Build openssl rpm
              run: |
                echo "Installing mock"
                dnf -y install epel-release
                dnf -y install mock rpm-build
                echo "Running mock build"
                mock -r .mock-config/rocky-lts92-x86_64.cfg --spec="./SPECS/openssl.spec" --sources="./SOURCES"
                echo "Extracting FIPS module from RPM"
                